### ISSUE TITLE
[EPIC] Add functionality to run triggers before and after components are run

### ISSUE THREAD

**Issue by shreyashankar** [loglabs/mltrace#226]
## Story

We want a user to be able to run predefined computation before and after their components are run. This would help users flag errors that can only be noticed at runtime (e.g., missing data, schema validation). The scope for this ticket is stateless computation within a single component run (i.e. if we are writing computation in the `beforeRun` for a preprocessing component, we will not look at the history of those component runs).

## Goals

- Executing triggers automatically at component runtime
- Logging information that results from these triggers to the mltrace db
- API to querying trigger results (in `client.py`)

## Tasks

- [x] #227
- [x] Write class/method stubs in the codebase
- [x] Fill out stubs
- [x] Write & run tests
