### ISSUE TITLE
[EPIC] Store artifacts for users

### ISSUE THREAD

**Issue by shreyashankar** [loglabs/mltrace#246]
So the user does not have to manually specify all inputs and outputs, we can load and save artifacts for them. The challenge here is to incorporate this I/O with tracing functionality. We will need to do the following:

- [x] #247
- [x] #248
- [x] While tracing, do the following:
  - [x] look for any dataframes or models and automatically create IOPointers for those
  - [x] if the user calls the `mltrace.log` or `mltrace.read` in their function, create IOPointers for those
  - [x] hash inputs, if there is a match with unique component name then automatically add as input IOPointer
